name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: arbmind/cmake-clang:latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=clang++

    - name: Build
      run: |
        cd build
        cmake --build . -- -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest